apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: goatcounter
resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - secret.yaml
  - pvc-tools.yaml
  - cronjob.yaml
