apiVersion: v1
kind: Service
metadata:
  name: goatcounter
  namespace: goatcounter
spec:
  selector:
    app: goatcounter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: goatcounter
  type: ClusterIP
