---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: libreddit
  namespace: libreddit
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
    # nginx.ingress.kubernetes.io/auth-type: basic
    # nginx.ingress.kubernetes.io/auth-secret: auth-secret
    # nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    # nginx.ingress.kubernetes.io/limit-rps: "10"
spec:
  rules:
  - host: libreddit.brennoflavio.com.br
    http:
      paths:
      - path: /vid
        pathType: Prefix
        backend:
          service:
            name: libreddit
            port:
              number: 8080
      - path: /
        pathType: Prefix
        backend:
          service:
            name: libreddit
            port:
              number: 8081
  tls:
  - hosts:
    - libreddit.brennoflavio.com.br
    secretName: libreddit-tls
