apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-cpp
  namespace: ai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: llama-cpp
  template:
    metadata:
      labels:
        app: llama-cpp
    spec:
      containers:
      - name: llama-cpp
        image: ghcr.io/ggml-org/llama.cpp:server
        args:
          - "--model"
          - "/models/qwen-3b.gguf"
          - "--threads"
          - "8"
          - "--ctx-size"
          - "32768"
          - "--port"
          - "8080"
          - "--jinja"
          - "--grammar-file"
          - "/models/json.gbnf"
        volumeMounts:
          - name: models
            mountPath: /models
        resources:
          limits:
            cpu: 12000m
            memory: 12000Mi
          requests:
            cpu: 8000m
            memory: 8000Mi
        ports:
          - containerPort: 8080
      volumes:
        - name: models
          persistentVolumeClaim:
            claimName: models
