apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minatto
resources:
  - namespace.yaml
  - gcr-secret.yaml
  - backend-pvc.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - backend-ingress.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - frontend-ingress.yaml
