---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: "minatto-4-preview"
resources:
    - namespace.yaml
    - gcr-secret.yaml
    - image-update-automation.yaml
    - ingress.yaml
    - deployment.yaml
    - service.yaml
    - image-repository.yaml
    - image-policy.yaml
