apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: github-runner
resources:
  - namespace.yaml
  - repository.yaml
  - release.yaml
secretGenerator:
  - name: github-runner-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
