apiVersion: v1
kind: Secret
metadata:
    name: google-smarthome-integration-secrets
    namespace: google-smarthome-integration
type: Opaque
stringData:
    GOOGLE_CALENDAR_ID: ENC[AES256_GCM,data:4UXDUXZrBiPH73w+c7W5DCOvlf/GYw4i6L0g,iv:VOzvWaBIAWFBI+xyOZwVq2sYK5UCMB4k1YV9PR93c0k=,tag:bMP+f6ZWUvLLYJj3lnWyyQ==,type:str]
    NEXTCLOUD_CALENDAR_URL: ENC[AES256_GCM,data:zqP19hPL45KiAaleP31TR9bi9S+IRl4UxAUd8Qgs7SK0KM7QHYa+aGGcLW+6Svt/zNiZKTi6OUap7nGBElhBtgpGzOiBtQ==,iv:fZsELPhSzVCSBDOc7ufyPsJVyaZqenKCmaiOYr05W78=,tag:nMp5jhsB71M0wYbClx5lzw==,type:str]
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:xYLJdO5m,iv:dE9WHBnt/TNBkOSduWk4vjp7FIi/bCXM8VYAy/23dzA=,tag:h1jWpjPCZ7fdE0WracrK3A==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:QL98UoR6IE4sg4SPpK8=,iv:tsNxZa03YG54he86E006Wl67VPwyfMRse39W/+NlCC4=,tag:i+sw1WSbYxvqF8GwyRLptw==,type:str]
    NEXTCLOUD_CALENDAR_NAME: ENC[AES256_GCM,data:AwxY0QnNImU=,iv:HsTmnWVfKrKH3Lyg2R1EwKGtSEjLWhniZlck1yZF3to=,tag:7eYCkPkih5hXtX8ra7nEUQ==,type:str]
    NEXTCLOUD_TASK_LIST_NAME: ENC[AES256_GCM,data:51JmHvs=,iv:97hRz57hKFcnjzcMpt4MnuavfUdUQ0cB/oulPu/zoK0=,tag:VWwZyGzN9P60XMlUqfgPdA==,type:str]
    GOOGLE_TASKLIST_NAME: ENC[AES256_GCM,data:cpcFWGQ7xBQ=,iv:Klye0gqGmNvDwJ1dtCYfliN+rFPqMmRyZT/+O8ymAto=,tag:nk2IXH1hWZQV2v5pOJ7xAA==,type:str]
    SECRET_ID: ENC[AES256_GCM,data:XETjugmVa5EDQH8VVZhtB685VIqoilPlUCNHxehoArk=,iv:OkR9HhToCE7Sd4g3gtsZdKtFV53vSArtfXNGKTyu+tg=,tag:YT3XhgKwTAI0rOPwHxHkyg==,type:str]
    GOGLE_AUTHORIZED_USER_FILE: ENC[AES256_GCM,data:wxCle54g1N7zbJbKTwEukUXZIkg+,iv:iVBxEn0qwWzCudcgVkkf/6DQF4lqbwrPAKzgWqwYefc=,tag:/sdTjCeC4rZeWgepeR7Czw==,type:str]
    GOOGLE_OAUTH_SECRET_FILE: ENC[AES256_GCM,data:6T56gVL8BtTN5l56UhuXet7aLWcntbJ+C8El4TvhNxId+toHZ+lGEylgzDAGkcjfuQLXpTiOWqzk9MwsYNsWx1N1MQyEQnZipyrH2LRIqEda0g0HB5sMW3L+QN2WwMcij5NbPqta+g==,iv:zvdHLHdcOXKxhrC222jzUZ+C2PQNJtdkXRKL403JQV0=,tag:o0JEp+rD96jSOZ94uhHyqg==,type:str]
    APP_USER: ENC[AES256_GCM,data:yXen1LGCRHVBtBxgf23KcpYCQyDByzJ7bhnz,iv:t1VjqJUaoWT07H8HL5g55l8BfJEhGdgFmnDXHweuA8s=,tag:FrTu52zcHuJCHGMoL7cXjQ==,type:str]
    APP_PASSWORD: ENC[AES256_GCM,data:vkGvc5YVmDA=,iv:Pfk8nSQZdXdOvBL5VpjGIju4pJARNLuIDJGYdbRRb+8=,tag:7b2kqDuUIIIO+TwqSps1EA==,type:str]
    GOOGLE_KEEP_MASTER_TOKEN: ENC[AES256_GCM,data:9S7ouqRyYmJpEARRJ3LrVqt9+ilAT7lsfZK2WQ6yuhZmpyDIoKNkoMMgh/PtqvN1sbnTpJDXNR+yIK135nDViBEvXBNbIdt+0r4asl7wnG7YuB0NLVoIp/rJixz5k8lqfgTmphEverMcE4zlH+bTY36KzS9OuAoo7ATp7z585oUzRNvzvpQhSUN8tT54IeMVpq7kVoBCWQJv64gwk0f2lzr58IqaB0VA1jYQXlL74d0M5KtkGbaVba0r0oQmmtIOYWXsPLEmXZ6PRGipe5u+gESjj5+lg5uP/Rh6rKaAtw==,iv:CufA4RCZewLE09OSXFB84Os9nvZ7nNQtlFmWKAfPe88=,tag:uzPu5SC9yRHhLhC+e6Yf5g==,type:str]
    GOOGLE_KEEP_USER: ENC[AES256_GCM,data:lzViyIFsLBwOfDng41JGzSi6K9Jb91DDExOJ,iv:ubf33m5KOT3tcLlRUlSMH3h5GCM40OLUpFd6edn9Gmc=,tag:5RgrMis8ZxKjiHp77LDQSw==,type:str]
    GOOGLE_KEEP_SHOPPINGLIST_NAME: ENC[AES256_GCM,data:MW2T5c6EgA==,iv:82KYNJ560La7h6ggL9epyamXLvpBU/47q1juuENSgSc=,tag:t204+uxf2ZlI4XQ1x3DzhQ==,type:str]
    NEXTCLOUD_SHOPPING_LIST_NAME: ENC[AES256_GCM,data:9+Bxk+wTcA==,iv:t6ff7f6kOw5+oSQsv0DkAdW8nuJnUni57IuKBgR1aX8=,tag:JPyXTn7LPgo3BWLbuOllMg==,type:str]
    NEXTCLOUD_URL: ENC[AES256_GCM,data:jWuMvrmWnYapRN682ICtJFfxdGlSYaMILhltcq0YCgFCapiETg==,iv:iCZ+GJzhSJdqO/TYn0+79V1vfdE05JeWoJTy7oJsz10=,tag:SJVkZpXxh6qRIHi2UViFNw==,type:str]
    GOOGLE_TASKS_DO_NOT_SYNC: ENC[AES256_GCM,data:5Q5fDUpf+/ANinXe5JQ=,iv:zvclhFlMxfwDj4PEBmCtFxMJDCzO03ll8sQwnJurgNU=,tag:1bjdguVWKdKVV2lugPhWPQ==,type:str]
    NEXTCLOUD_LIST_REGEX: ""
sops:
    lastmodified: "2026-02-28T02:34:41Z"
    mac: ENC[AES256_GCM,data:xdw9Eyi2uBfRaBf6icW7JxgxasbuWSdO0GKJd67Zj/SM6mwaNjEcv8PWq1Zf7J4ArtKoEScn3l4rKVBKocm9ijHEvnLF2707nnjlH81moD9ZSTSuD+hZLWNcED7AmmDmbKCDxbtfWe+wPMGoIgUVG0UYo4E1bkgiuAPJKQbyzH8=,iv:6bB4DWe9HHLS2f1RfhMvMjQnTsC02oCLAR/K+luVsC4=,tag:Kuo9dZb0b1ChtTNDROdjDw==,type:str]
    pgp:
        - created_at: "2025-01-17T04:09:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQIMA4o7DJvx8F4XAQ/+NzKLvd4ynPHdLLc0p4SSZ7T+tdZALkXeUoBjhqlJRUVL
            GcdSQdgasP05vBx/IFoXfJpYqOhCKQp9DSwrIASFsqj7nn11teHjo/l/0wmf6K2K
            pJcssopsz3N5PT190q/IF1+kzaLTZjk7Fws44piCTf+3uqXnKXUECd097Y68VeyG
            OYps6t03swz7aYOYTugG5jtt6ALImYPTevzfmIpBTuoroIwpISIFdBDRbBkVRGnD
            6eCMoajEZkOQ0L6fMm3qvJ5RTPrgdHnZWndJXQRXTc/OirooztOKC/TDOLF9GH0G
            YV40A1uJTXof6myRGLrlsuJNYTQxzR5WLct6uUOLNYrc1XWm1qvneN0Sm2UDBXnR
            5BYZsaCzbYgl+rl2y2agaKJZR7NoSZfrdrwfUBaxj0TgDi/VDzecK+h4Fpy8L7PF
            b986pTZKE/PKRrDXDvgWEinE95FlmMhYuzmaL2XHRs07Kj2OdyM1IXhZrucMG6Zx
            2PtajsPIQrA+BHbLisy/pUVFgC3ODC6eQ4aAfKDxTjnBlI+7KgM0ZPWsY58ji+XZ
            sctg1AfySD/34sojj8F/d3r1w5MflZZ+vWG74mcg4EsUsB0pZ9UHoiIgLZyNj8t3
            Ew8wjVWa6wu4xc9kTgsZST3o8qUHn8DGvcIfADltcsPAA3MHiBgKe2c4VjzZAszU
            ZgEJAhAScfNQDYhmhUU3TmRKsTc6+T2OC7nivfGPLkAco4M0BG/54DMOKmGHRfqr
            X7H7W2cSErb6/g9rOACecTLggqHSTSaBnmui1SAiYPlq4o5ElC7Wjdf5aE2g/4C/
            pEL8hPPrHA==
            =71tg
            -----END PGP MESSAGE-----
          fp: 6357449C423960593235FB6BE056C483022CCA1B
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
