---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich-kiosk
  namespace: immich-kiosk-joao
  annotations:
    cert-manager.io/cluster-issuer: lets-encrypt
    external-dns.alpha.kubernetes.io/target: "brennoflavio.com.br"
spec:
  rules:
  - host: joao.brennoflavio.com.br
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: immich-kiosk
            port:
              number: 3000
  tls:
  - hosts:
    - joao.brennoflavio.com.br
    secretName: kiosk-tls
